-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pokemon.Object exposing (..)


type Attack
    = Attack


type Pokemon
    = Pokemon


type PokemonAttack
    = PokemonAttack


type PokemonDimension
    = PokemonDimension


type PokemonEvolutionRequirement
    = PokemonEvolutionRequirement
