-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pokemon.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Pokemon.Scalar exposing (defaultCodecs)


type alias Id =
    Pokemon.Scalar.Id


codecs : Pokemon.Scalar.Codecs Id
codecs =
    Pokemon.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
