-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pokemon.Union exposing (..)


placeholder : String
placeholder =
    ""
