-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pokemon.Object.PokemonDimension exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Pokemon.InputObject
import Pokemon.Interface
import Pokemon.Object
import Pokemon.Scalar
import Pokemon.ScalarCodecs
import Pokemon.Union


{-| The minimum value of this dimension
-}
minimum : SelectionSet (Maybe String) Pokemon.Object.PokemonDimension
minimum =
    Object.selectionForField "(Maybe String)" "minimum" [] (Decode.string |> Decode.nullable)


{-| The maximum value of this dimension
-}
maximum : SelectionSet (Maybe String) Pokemon.Object.PokemonDimension
maximum =
    Object.selectionForField "(Maybe String)" "maximum" [] (Decode.string |> Decode.nullable)
