-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Pokemon.Object.PokemonEvolutionRequirement exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Pokemon.InputObject
import Pokemon.Interface
import Pokemon.Object
import Pokemon.Scalar
import Pokemon.ScalarCodecs
import Pokemon.Union


{-| The amount of candy to evolve
-}
amount : SelectionSet (Maybe Int) Pokemon.Object.PokemonEvolutionRequirement
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


{-| The name of the candy to evolve
-}
name : SelectionSet (Maybe String) Pokemon.Object.PokemonEvolutionRequirement
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
